### ISSUE TITLE
input system

### ISSUE THREAD

**Issue by MarinMizuri** [KlavierGayming/K-Dev-Android#2]
idk i feel like the input system in demo 1 felt way smoother compared to the latest demos, when i play fast songs sometimes the notes wouldn't hit when i wanted it to.

**Comment by bluewastaken01** [comment]
Same

**Comment by zacksgamerz** [comment]
We havent changed anything so idk what you're talking bout tbh

**Comment by Ali109956** [comment]
This is what happens to me as well

**Comment by KlavierGayming** [comment]
we haven't changed shit about the input system though

**Comment by BoyfriendFNF** [comment]
> we haven't changed shit about the input system though

well apperantly spamming is no longer op because when I ironically spam it is bugged and misses alot

**Comment by MarinMizuri** [comment]
yeah since that also affects difficult and fast songs. ex: tricky, matt, zardy and since those songs have a lot of spammy parts (especially matt) it bugs and not hit notes on stairs or note spams

**Comment by zacksgamerz** [comment]
Once AGAIN.
Im telling you its ninjamuffin's fault for programming the note register system using stupid if statements and not math.
We havent touched anything so stop blaming us.
-_-

**Comment by Pixelneery** [comment]
Yea, they haven't touched anything

**Comment by ElPeppyWall** [comment]
Little man

**Comment by bluetoot420** [comment]
ok zack 👍

**Comment by BoyfriendFNF** [comment]
> Once AGAIN.
> Im telling you its ninjamuffin's fault for programming the note register system using stupid if statements and not math.
> We havent touched anything so stop blaming us.
> -_-

ok

**Comment by PRIVATEAlpha5** [comment]
ok

**Comment by RoadRings** [comment]
> ok

Ok

**Comment by BoyfriendFNF** [comment]
> > ok
> 
> Ok

OK
