### ISSUE TITLE
BUG!

### ISSUE THREAD

**Issue by King-Fox-Yt** [KlavierGayming/K-Dev-Android#6]
**this issue has duplicates?**
bug is can't enter the game

**Describe the bug**

**To Reproduce**

**Expected behavior**
my friend can't enter kade engine
![Screenshot_20210514-225052](https://user-images.githubusercontent.com/83482176/118335239-1ebc7d80-b507-11eb-93bf-ac2fe412540f.png)

**Screenshots**

**Additional context**
my friend tell me he have a bug on kade engine

**Comment by KlavierGayming** [comment]
You provided literally no details. Closing.
