### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BoyfriendFNF** [KlavierGayming/K-Dev-Android#7]
**this issue has duplicates?**
Black textures - https://github.com/luckydog7/Funkin-android/issues/12 (max texture size problem)
Crash - https://github.com/luckydog7/Funkin-android/issues/10 (ram problem)

**Describe the bug**
When losing, there's no death icon 
**To Reproduce**
1. Go to any song 
2. Get to a low amount of hp 
3. Theres no death icon for Boyfriend 

**Expected behavior**
Death icon showing up

**Comment by EyadTaher** [comment]
so that means theres no death icon?

**Comment by KlavierGayming** [comment]
The health icon is there, tho for some reason it doesn't work. I have no idea how to fix, closing.
